# Examples using poetry in github workflows: https://github.com/snok/install-poetry?tab=readme-ov-file#workflow-examples-and-tips

name: Create and Commit File on First of Month
on:
  schedule:
    # At 00:00 on Sunday (once a week)
    - cron: '0 0 * * 0'
permissions:
  contents: write
jobs:
  create-and-commit-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.2
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Create GHG plots
      run: |
        source $VENV
        python make_ghg_plots.py

    - name: Create Vehicle Registrations plots
      run: |
        source $VENV
        python make_ev_registration_plots.py

    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Commit and push
      run: |
        echo "Automated plots update: $(date '+%Y-%m-%d')"
        git commit -am "Automated plots update: $(date '+%Y-%m-%d')"
        git push origin main