name: Create and Commit File on First of Month
on:
  schedule:
    # At 00:00 on day-of-month 1
    - cron: '0 0 1 * *'
permissions:
  contents: write
env:
  POETRY_VERSION: '1.7.1'
jobs:
  create-and-commit-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ env.POETRY_VERSION }}

    - name: Create GHG plots
      run: |
        poetry install
        python make_ghg_plots.py

    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Commit and push
      run: |
        echo "Automated plots update: $(date '+%Y-%m-%d')"
        git commit -am "Automated plots update: $(date '+%Y-%m-%d')"
        git push origin main